todoproject/todoapp/urls.py
from django.contrib import admin
from . import views
from django.urls import path, include
app_name='todoapp'
urlpatterns = [
    path('',views.priority,name='priority'),
    path('delete/<int:taskid>/',views.delete,name='delete'),
    path('update/<int:id>/', views.update, name='update'),
    path('cbvhome/',views.TaskListView.as_view(),name='cbvhome'),
    path('cbvdetail/<int:pk>/',views.TaskDetailView.as_view(),name='cbvdetail'),
    path('cbvupdate/<int:pk>/', views.TaskUpdateView.as_view(), name='cbvupdate'),
    path('cbvdelete/<int:pk>/', views.TaskDeleteView.as_view(), name='cbvdelete')

]

todoproject/todoproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todoapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todoproject/todoapp/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    name=models.CharField(max_length=250)
    priority=models.IntegerField()
    date=models.DateField()
    def __str__(self):
        return self.name

todoproject/todoapp/views.py
from django.shortcuts import render, redirect
from django.urls import  reverse_lazy

from .form import TodoForm
from.models import Task
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView,DeleteView

class TaskListView(ListView):
    model=Task
    template_name = 'home.html'
    context_object_name = 't1'
    success_url = reverse_lazy('todoapp:cbvhome')

class TaskDetailView(DetailView):
    model=Task
    template_name = 'detail.html'
    context_object_name = 'task'

class TaskUpdateView(UpdateView):
    model=Task
    template_name = 'edit.html'
    context_object_name = 'task'
    fields = ('name','priority','date')

    def get_success_url(self):
        return reverse_lazy('todoapp:cbvdetail',kwargs={'pk':self.object.id})

class TaskDeleteView(DeleteView):
    model=Task
    template_name ='delete.html'
    success_url = reverse_lazy('todoapp:cbvhome')
# Create your views here.
def priority(request):
    task1 = Task.objects.all()
    if request.method=='POST':
        name = request.POST.get('name')
        priority = request.POST.get('priority')
        date=request.POST.get('date')
        task=Task(name=name,priority=priority,date=date)
        task.save()
    return render(request,'home.html',{'t1':task1})

def delete(request,taskid):
    task=Task.objects.get(id=taskid)
    if request.method=='POST':
        task.delete()
        return redirect('/')

    return render(request,'delete.html')

def update(request,id):
    t1=Task.objects.get(id=id)
    f1=TodoForm(request.POST or None, instance=t1)
    if f1.is_valid():
        f1.save()
        return redirect('/')
    return render(request,'update.html',{'f1':f1,'t1':t1})

todoproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Task</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous"><body>
<link rel="stylesheet" href="{% static 'static.css' %}">
{% block content %}
{% endblock %}
</body>
</html>

todoproject/templates/delete.html
{% extends 'base.html' %}
{% block content %}

<form method="POST">
    {% csrf_token %}
    <br>
    <p>Are you sure this task is done????</p>
    <button class="btn btn-success">Confirm</button>
</form>
{% endblock %}

todoproject/templates/detail.html
{% extends 'base.html' %}
{% block content %}


<div class="shadow card">
                <div class="card-body">
                    <div class="card-title">
                       <h4> {{task.name}}</h4>
                    </div>
                        <p><b>{{task.priority}}</b></p>
                        <p><b>{{task.date}}</b></p>
                    <a class="btn btn-danger" href="{% url 'todoapp:delete' task.id %}">Done</a>
                    <a class="btn btn-success" href="{% url 'todoapp:update' task.id %}">Update</a>

                </div>
            </div>
{% endblock %}

todoproject/templates/edit.html
{% extends 'base.html' %}
{% block content %}
<div class="card">
  <div class="class-header">
    <div class="class-title">
      <h1><u>Task Update....</u></h1>
    </div>
    <div class="class-body">
    <form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button class="btn btn-success">Confirm</button>
</form>
      </div>
  </div>
</div>

{% endblock %}

todoproject/templates/home.html
{% extends 'base.html' %}
{% block content %}
<br>
<div class="container-fluid">
    <div class="col-md-12"></div>
        <div class="banner">
            <div class="banner-text">
            <h2>TASK</h2>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form method="POST" class="p-3 shadow">
            {% csrf_token %}
                <div class="form-group">
                    <input type="text" class="form-control" name="name" placeholder="Enter name"><br>
                </div>

                <div class="form-group">
                    <input type="text" class="form-control" name="priority" placeholder="Enter your priority"><br>
                </div>

                <div class="form-group">
                    <input type="date" class="form-control" name="date" placeholder="Enter your date"><br>
                </div>
                <input type="submit" class="btn btn-success">
            </form>
        </div>

        <div class="col-md-6">
            <h3><u>Task to be completed</u></h3>
            {% for i in t1 %}

            <div class="shadow card">
                <div class="card-body">
                    <div class="card-title">
                       <h4> {{i.name}}</h4>
                    </div>
                        <p><b>{{i.priority}}</b></p>
                        <p><b>{{i.date}}</b></p>
                    <a class="btn btn-danger" href="{% url 'todoapp:delete' i.id %}">Done</a>
                    <a class="btn btn-success" href="{% url 'todoapp:update' i.id %}">Update</a>

                </div>
            </div>
            <br>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

todoproject/templates/update.html
{% extends 'base.html' %}
{% block content %}

<form method="POST">
    {% csrf_token %}
    <br>
    {{f1.as_p}}
    <button type="submit" class="btn btn-success">Confirm</button>
</form>
{% endblock %}