myproduct/product_project/product_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('productapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproduct/product_project/productapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
app_name="productapp"
urlpatterns = [

    path('',views.home,name='home'),
    path('product/<int:id>/',views.detail,name='detail'),
    path('add/',views.add,name='add'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

myproduct/product_project/productapp/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    bname=models.CharField(max_length=250)
    bdesc=models.TextField()
    byear=models.IntegerField()
    bimg=models.ImageField(upload_to="gallery")

    def __str__(self):
        return self.bname

myproduct/product_project/productapp/forms.py
from django import forms
from .models import Book

class BookForm(forms.ModelForm):
    class Meta:
        model=Book
        fields=['bname','bdesc','byear','bimg']

myproduct/product_project/productapp/views.py
from django.shortcuts import render, redirect
from .forms import BookForm
from . models import Book

# Create your views here.
def home(request):
    book = Book.objects.all()
    context={

        'booklist': book
    }
    return render(request,'home.html',context)

def detail(request,id):
    pd=Book.objects.get(id=id)
    return render(request,'detail.html',{'pd':pd})

def add(request):
    if request.method=="POST":
        name=request.POST.get('name',)
        desc = request.POST.get('desc',)
        year = request.POST.get('year',)
        img = request.FILES['img']
        pd=Book(bname=name,bdesc=desc,byear=year,bimg=img)
        pd.save()
    return render(request,'add.html')

def update(request,id):
    pd=Book.objects.get(id=id)
    form=BookForm(request.POST or None,request.FILES,instance=pd)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'update.html',{'form':form,'pd':pd})

def delete(request,id):
    if request.method=='POST':
        pd = Book.objects.get(id=id)
        pd.delete()
        return redirect('/')

    return render(request,'delete.html')

myproduct/product_project/templates/add.html
{% extends 'base.html' %}

{% block body %}

<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" name="name" placeholder="Enter Book Name"><br><br>
  <input type="text" name="desc" placeholder="Enter Book Description"><br><br>
  <input type="text" name="year" placeholder="Enter Year"><br><br>
  <input type="file" name="img" ><br><br>
  <input class="btn btn-warning" type="Submit" >
</form>

{% endblock %}

myproduct/product_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Online Book Reference
  </a>
</nav>
 {% block body %}
{% endblock %}
</body>
</html>

myproduct/product_project/templates/delete.html
{% extends 'base.html' %}

{% block body %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    Are you want to delete the data?
    <input class="btn btn-warning" type="submit">
</form>

{% endblock %}

myproduct/product_project/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<br>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{pd.bimg.url}}" width="400" height="400">
        </div>
        <div class="col-md-6" style="align:right">
            <h4>{{pd.bname}}</h4><br>
            <h5>Description: {{pd.bdesc}}</h5><br>
            <h5>Year: {{pd.byear}}</h5>
            <br>
            <a class="btn btn-warning" href="{% url 'productapp:update' pd.id %}">Update</a>
            <a class="btn btn-danger" href="{% url 'productapp:delete' pd.id %}">Delete</a>
        </div>
    </div>
</div>
{% endblock  %}

myproduct/product_project/templates/home.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        {% for i in booklist %}
        <div class="col-md-3">
            <div class="card" style="width: 15rem; height: 29rem">
  <img class="card-img-top" src="{{i.bimg.url}}" width="50" height="130" alt="Card image cap">
  <div class="card-body" >
    <h5 class="card-title">{{i.bname}}</h5>
    <p class="card-text">{{i.bdesc}}</p>
    <a href="{% url 'productapp:detail' i.id %}" class="btn btn-primary">Details</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
</div><br><br>
<div align="center" >
    <a class="btn btn-info" href="{% url 'productapp:add' %}" >Add</a>
</div>
{% endblock %}

myproduct/product_project/templates/update.html
{% extends 'base.html' %}

{% block body %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input class="btn btn-warning" type="submit">
</form>

{% endblock %}